version: "3.8"
services:
  api:
    build: .
    container_name: circuit-connect-api
    ports:
      - "8089:8088"
    env_file:
      - .env
    networks:
      - cdc-realtime-pipeline_cdc-network
      - postgres_net
    restart: unless-stopped
networks:
  cdc-realtime-pipeline_cdc-network:
    external: true
  postgres_net:
    external: true
